[package]
name = "music_trainer"
version = "0.1.0"
edition = "2021"

[dependencies]
cpal = "0.15.3"
eframe = "0.30.0"
egui = "0.30.0"
egui_extras = "0.30.0"
env_logger = "0.11.6"
hound = "3.5.1"
itertools = "0.14.0"
rand = "0.9.0"
